name: PRCheck
run-name: "PR ${{ github.event.number }} Check(${{github.event.action}}) by ${{ github.actor }}"
on:
  pull_request_target:
    types: [ opened, reopened, synchronize, labeled ]

jobs:
  Setup:
    runs-on: ubuntu-latest
    steps:
      - id: setup
        run: |
        
          echo "Labeling"
          gh pr edit --repo ${{ github.repository }} \
            --add-label duplicate \
            ${{ github.event.number }} || :
