name: PRMerge
run-name: "PR ${{ github.event.number }} Merge by ${{ github.actor }}"
on:
  pull_request_target:
    types: [ labeled ]

jobs:
  Setup:
    runs-on: ubuntu-latest
    steps:
      - id: setup
        run: |
        
          echo "Labeling"
          gh pr edit --repo ${{ github.repository }} \
            --add-label bug \
            ${{ github.event.number }} || :
